# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'https://github.com/innovatrics/innovatrics-podspecs'
source 'https://github.com/vladyslav-shkoda/sdk-kyc-podspecs.git'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'kyc-sdk'
  use_frameworks!

  # Pods for Runner

end
